# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bulgarian Utility Outage Checker
version: "1.1.2"
slug: bulgarian_utility_outage_checker
description: Check for planned and unplanned utility outages in Bulgaria
url: "https://github.com/reminchev/bulgarian_utility_outage_checker"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  check_interval: 3600
schema:
  identifier: "str"
  check_interval: "int(60,3600)?"
# Uncomment the line below for production builds
# image: "ghcr.io/reminchev/{arch}-addon-bulgarian-utility-outage-checker"



