# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bulgarian Utility Outage Checker / Проверка за Аварии На комуннални услуги в България
version: "1.0.0"
slug: bulgarian_utility_outage_checker
description: Checks for planned and unplanned power outages from ERM West / Проверява за планирани и аварийни прекъсвания на електрозахранването
url: "https://github.com/reminchev/bulgarian_utility_outage_checker"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  check_interval: 3600
schema:
  identifier: "str"
  check_interval: "int(60,3600)?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
